### ISSUE TITLE
A word of thanks

### ISSUE THREAD

**Issue by stanislaw** [jedrzejboczar/elf-size-analyze#22]
Dear @jedrzejboczar,

I could not find a better place to write this message, so I am opening it here and closing it right away to not mess up with your open issues :smile: 

Your script has been very instrumental in my analysis of embedded software binaries at work. To give you a small insight into the type of work we are doing, we had to strip the unnecessary code from our flight software binaries, and this is where your HTML visualization was especially useful. The workflow I was following was pretty simple: I printed the script's HTML output to PDF and went to highlight the most obvious candidates for removal from the flight executable along with the sizes that these components consume. After I had highlighted everything, I could quickly collect the candidate components and the total size that could be saved by removing all unused code. The HTML-to-PDF experience made the process very UX-friendly.

Thanks for putting this script together. It is definitely very useful.

Cheers,
Stanislav (Reflex Aerospace GmbH)

**Comment by jedrzejboczar** [comment]
@stanislaw Thank you, I'm glad that it was helpful. Also, credits to @dkuschmierz who added the HTML export feature.
