### ISSUE TITLE
html output failed for non-english enviroment

### ISSUE THREAD

**Issue by dotnfc** [jedrzejboczar/elf-size-analyze#23]
`
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 477: illegal multibyte sequence
`

it can be solved by (html/gen.py)
`
def generate_html_output(node_dict, title, custom_css=None):
    table_content = ""

    custom_css = custom_css or DEFAULT_CSS
    with open(custom_css, encoding='utf-8') as f:
        css_styles = f.read()

    with open(JAVASCRIPT, encoding='utf-8') as f:
        javascript = f.read()
... ...
`
open file with utf-8 encoding.

**Comment by jedrzejboczar** [comment]
Thanks
