### ISSUE TITLE
LLVM doesn't support nm --line-numbers option

### ISSUE THREAD

**Issue by dlech** [jedrzejboczar/elf-size-analyze#24]
I tried running this but got the following error:

```console
C:/msys64/clang64/bin/nm.exe: error: : unknown argument '--line-numbers'
Traceback (most recent call last):
  File "/home/david/.local/pipx/.cache/640b108cb1cbb91/bin/elf-size-analyze", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/david/.local/pipx/.cache/640b108cb1cbb91/lib/python3.11/site-packages/elf_size_analyze/__main__.py", line 72, in main
    fileinfo = extract_elf_symbols_fileinfo(args.elf, get_exe('nm'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/.local/pipx/.cache/640b108cb1cbb91/lib/python3.11/site-packages/elf_size_analyze/symbol.py", line 177, in extract_elf_symbols_fileinfo
    raise subprocess.CalledProcessError(nm_proc.returncode,
subprocess.CalledProcessError: Command '['nm', '--portability', '--line-numbers', '_build/projection-clang64-install/winrt/_winrt.pyd']' returned non-zero exit status 1.  
```

Apparently the LLVM version of `nm` does not support the `--line-numbers` option. https://github.com/llvm/llvm-project/issues/39348

Is there a workaround?

**Comment by jedrzejboczar** [comment]
@dlech Could you give this a try? https://github.com/jedrzejboczar/elf-size-analyze/pull/25
This is a quick fix, it should first call `nm --version` and try to detect if using `llvm-nm`, then it uses different regex for parsing. However, I don't think you can get line numbers using `llvm-nm`, just file names. Please check if there are no issues with other llvm binutils as I tested only `nm`.

**Comment by dlech** [comment]
Thanks! I've confirmed that it fixes the crash.

(I still haven't managed to get useful output because likely because `nm` reports the size is 0 on all symbols for some reason but I will have to look into that some other time)

**Comment by jedrzejboczar** [comment]
@dlech I've merged the fix for now as from my testing on some example ELF file it worked correctly with llvm-nm
