### ISSUE TITLE
[Feature] generate report in json format

### ISSUE THREAD

**Issue by ghost** [jedrzejboczar/elf-size-analyze#5]
The `size_report` tool support so generate json reports. Would be great to see this here too to further process the reports.

**Comment by jedrzejboczar** [comment]
This would be nice to have, but I don't think I'll find time to add this anytime soon, as I wouldn't really use it anyway. But any PRs are welcome. It's probably a matter of properly serializing the class `SymbolsTreeByPath`.

**Comment by jedrzejboczar** [comment]
This is now possible using `-j`/`--json`.
